name: hoox
channels:
  - conda-forge
  - bioconda
dependencies:
# Dependencies
  - snakemake
  - fd-find
  - ncbi-datasets-cli
  - r-base
  - r-tidyverse
  - r-data.table
  - httplib2 # install-iscan
  - aria2 # install-iscan
  - openjdk # install-iscan
  - zlib # R dependency
  - unzip
  - biopython
  - r-seqinr
  - r-furrr
  - pyhmmer=0.10.14
# Development
  - ipython
  - black
  - isort
  - objprint
  - icecream
  - snakedeploy
  - snakefmt
