# Input genome list.
# It contains NCBI assembly accessions,
# one per line, it allows comments with '#'.
genomes:
  genomes.txt

# Directory of .hmm profiles.
queries:
  queries

# Where to store the results?
results:
  results

# Only use genomes
# from NCBI RefSeq assembly
only_refseq:
  false

# DO NOT trigger a fatal error
# on NO network access.
offline:
  false
