# Input genome list.
# It contains NCBI assembly accessions,
# one per line, it allows comments with '#'.
genomes:
  genomes.txt

# Directory of .hmm profiles.
queries:
  queries

# Where to store the results?
results:
  results

# Search this many
# neighbors upstream and downstream
# of any hit
n_neighbors:
  12

# Batch size
# for interpro runs
batch_size:
  8000

# Fasta formatting
# NCBI uses 80
# but it's usually 60
faa_width:
  80

# Only use genomes
# from NCBI RefSeq assembly
only_refseq:
  false

# DO NOT trigger a fatal error
# on NO network access.
offline:
  false


iscan_header:
  - pid
  - md5
  - len
  - analysis
  - memberDB
  - memberDB_txt
  - start
  - end
  - score
  - recommended
  - date
  - interpro
  - interpro_txt
  - GO
  - residue
