CDS_HEADER:
  - "genome"
  - "pid"
  - "gene"
  - "order"
  - "start"
  - "end"
  - "contig"
  - "strand"
  - "locus_tag"
  - "product"

BLAST_HEADER:
  - "qseqid"
  - "qlen"
  - "sseqid"
  - "slen"
  - "qstart"
  - "qend"
  - "sstart"
  - "send"
  - "qseq"
  - "sseq"
  - "full_sseq"
  - "evalue"
  - "bitscore"
  - "score"
  - "length"
  - "pident"
  - "nident"
  - "mismatch"
  - "positive"
  - "gapopen"
  - "gaps"
  - "ppos"
  - "qframe"
  - "btop"
  - "cigar"
  - "stitle"
  - "qcovhsp"
  - "scovhsp"

ISCAN_HEADER:
  - "pid"
  - "md5"
  - "length"
  - "analysis"
  - "memberDB"
  - "memberDB_txt"
  - "start"
  - "end"
  - "score"
  - "recommended"
  - "date"
  - "interpro"
  - "interpro_txt"
  - "GO"
  - "residue"

NEIGHS_HEADER:
  - "position"
  - "q_alias"
  - "query"
  - "row_cds"
  - "genome"
  - "pid"
  - "gene"
  - "order"
  - "start"
  - "end"
  - "contig"
  - "strand"
  - "locus_tag"
  - "product"
