CDS_HEADER:
  - "genome"
  - "pid"
  - "gene"
  - "order"
  - "start"
  - "end"
  - "contig"
  - "strand"
  - "locus_tag"
  - "product"

ISCAN_HEADER:
  - "pid"
  - "md5"
  - "length"
  - "analysis"
  - "memberDB"
  - "memberDB_txt"
  - "start"
  - "end"
  - "score"
  - "recommended"
  - "date"
  - "interpro"
  - "interpro_txt"
  - "GO"
  - "residue"
